#!/bin/bash
#
# foghorn - start and stop the foghorn service
#
# chkconfig: - 51 86
#
# description: foghorn listens for specific dbus signals and translates \
#              those signals into snmp traps.
#
# processname: foghorn
# pidfile: /var/run/foghorn.pid
#
### BEGIN INIT INFO
# Provides: foghorn
# Required-Start: $syslog messagebus snmpd
# Required-Stop: $syslog messagebus snmpd
# Default-Start:
# Default-Stop:
# Short-Description: start and stop foghorn service
# Description: The foghorn service listens for specific dbus signals \
#              and translates those signals into snmp traps.
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

exec="/usr/sbin/foghorn"
prog="foghorn"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog

start() {
    [ -x $exec ] || exit 5
    echo -n $"Starting $prog: "
    daemon $exec
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
	rh_status_q && exit 0
	$1
	;;
    stop)
	rh_status_q || exit 0
	$1
	;;
    restart)
	$1
	;;
    reload)
	rh_status_q || exit 7
	$1
	;;
    status)
	rh_status
	;;
    condrestart|try-restart)
	rh_status_q || exit 0
	restart
	;;
    *)
	echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
	exit 2
esac
exit $?
